### ISSUE TITLE
eshost "runtime" needs: realm creation API

### ISSUE THREAD

**Issue by rwaldron** [devsnek/engine262#23]
In order to implement a first class "runtime" for eshost, I need one of the following things exposed in the runtime's global object: 

- Realm
- Or, something like: https://github.com/devsnek/engine262/blob/c72261fcd4c5af1fb40231d956450025deab7062/src/engine.mjs#L113-L124

Thanks!

**Comment by devsnek** [comment]
@rwaldron i've added an api to handle realms here: https://github.com/devsnek/engine262/blob/4a6e11e0dc4f0852a9fdaec0b63dfe58e2808225/bin/engine262.js#L31-L39

is this good for what you need?

**Comment by rwaldron** [comment]
I pulled the latest master, `npm install`'ed and `npm run build`. I created a file called "realm.js" with the following contents: 

```js
print(typeof Realm);
print(typeof createRealm);
```

And ran it: 

```
engine262 ./test/realm.js
```

And the result is: 

```
$ engine262 ./test/realm.js
'undefined'
'undefined'
```

I need the Realm API available in the runtime :)

**Comment by devsnek** [comment]
ping @rwaldron

**Comment by devsnek** [comment]
ping @rwaldron

**Comment by rwaldron** [comment]
Sorry for the delay and thanks for implementing this. My one request is that you use the `$262` name instead of `$`.

**Comment by devsnek** [comment]
@rwaldron done :)
