### ISSUE TITLE
Figure out how to do parenthesized LHS correctly

### ISSUE THREAD

**Issue by TimothyGu** [devsnek/engine262#29]
Back story (https://github.com/estree/estree/issues/194): ESTree/Acorn doesn't provide us enough information to distinguish between

```js
fn = function () {};
```

and 

```js
(fn) = function () {};
```

causing [tc39/test262 `language/expressions/assignment/fn-name-lhs-cover.js`](https://github.com/tc39/test262/blob/f77b930e6720f8005d5302acaedd434e13bf2fe2/test/language/expressions/assignment/fn-name-lhs-cover.js) to fail. As https://github.com/estree/estree/issues/194 attempts to find a solution in ESTree, we should find a way to patch Acorn so that we have this information for ourselves _right now_.

@devsnek assigning this to you as you've done some Acorn work recently.

**Comment by TimothyGu** [comment]
Aha, Acorn provides a [`preserveParens`](https://github.com/acornjs/acorn/tree/master/acorn) option that we can use.

> If this option is `true`, parenthesized expressions are represented by (non-standard) `ParenthesizedExpression` nodes that have a single `expression` property containing the expression inside parentheses.

Shouldn't be too hard to fix the test then.

**Comment by devsnek** [comment]
Yes we should definitely use that option, otherwise we're missing https://tc39.github.io/ecma262/#sec-grouping-operator-runtime-semantics-evaluation
