### ISSUE TITLE
CLI support for -m or --module to evaluate .js as module

### ISSUE THREAD

**Issue by rwaldron** [devsnek/engine262#75]
Nearly all of the shells that eshost works with provides support for module evaluation via a flag, eg. `-m` or `--module`. I've written a small patch for engine262 to support both of those flags (while preserving the .mjs behavior), but wanted to open an issue before I went ahead with a PR. 

This is necessary because there is actually no specified requirement that modules must have .mjs, so all of Test262's tests, including module code, are in .js files.

**Comment by devsnek** [comment]
adding a --module seems fine to me

**Comment by rwaldron** [comment]
Excellent! I'll open the PR now :)
