### ISSUE TITLE
Issues disambiguating stdout contents

### ISSUE THREAD

**Issue by rwaldron** [devsnek/engine262#77]
All shells that eshost supports currently provide some distinguishable error stack output that can be easily disambiguated through some regular expression pattern matching process. Presently, engine262 prints all process output to `process.stdout`, so eshost must implement a `normalizeResult` method in the `ConsoleAgent` subclass for engine262. Unfortunately, there is no way to reliably disambiguate between, for example, the following values: 

```
foo\n
```

```
SyntaxError\n
```

I'm going to re-use the format and method that I used in a previous issue, as I think it was helpful to illustrate the issue: 

// code.js 
```js
eval("\'\u000Astr\u000Aing\u000A\'");
```

In node repl: 

```
$ node
> child_process.spawnSync("engine262", [ "./code.js" ]).stdout.toString()
'SyntaxError\n'
```

Compared to: 

...JSC: 

```
> child_process.spawnSync("jsc", [ "./code.js" ]).stdout.toString()
'Exception: SyntaxError: Unexpected EOF\nat ./code.js:7\neval@[native code]\nglobal code@./code.js:7:5\n'
```

...d8: 

```
> child_process.spawnSync("d8", [ "./code.js" ]).stdout.toString()
'undefined:1: SyntaxError: Invalid or unexpected token\n\'\n^\nSyntaxError: Invalid or unexpected token\n    at ./code.js:7:1\n\n'
```

All of the others have similar information that can be extracted and used to disambiguate. 

Now, if I had some code that produces stdout that is _not_ an error:

// code.js 
```js
print(1 === 1);
```

In node repl: 

```
$ node
> child_process.spawnSync("engine262", [ "./code.js" ]).stdout.toString()
'true\n'
```

I think there a few possible fixes: 

1. Move error output to `stderr` (but I think this might require quite a bit of refactoring work, I'm not sure)
2. Make all error output include certain standard pieces of information:
```
Error: message
    at file:N:N
```

For example, a SyntaxError on line 1, at character 1, in "foo.js"

```
SyntaxError: Invalid or unexpected token
    at foo.js:1:1
```

The same error, but from eval():

```
SyntaxError: Invalid or unexpected token
    at <eval>:1:1
```

I don't even think it has to be exactly like the examples I've given, but there needs to be some way to know the difference between the output of these: 

```
function MyError() {}
MyError.prototype.name = 'MyError';
throw new MyError();
```

```
print('MyError');
```

Presently, both produce `'MyError\n'` in engine262, whereas `eshost` needs something like: 

```
MyError: undefined
  at code.js:3:1
```

**Comment by devsnek** [comment]
moving to stderr would just be changing
```js
process.stdout.write(`${inspected}\n`);
```
to
```js
process.stderr.write(`${inspected}\n`);
````


> Make all error output include certain standard pieces of information:

there are currently stack traces in engine262, although i'm not certain of the exact logic i would need to display them on exit. Perhaps `'stack' in e ? e.stack : Error.prototype.toString(e)`?

**Comment by rwaldron** [comment]
> moving to stderr would just be changing

But I don't think you want to move _all_ process output to stderr, right? That's why I think it might be involved. You'd only want to move errors to stderr and keep normal output at stdout

**Comment by devsnek** [comment]
it would just move an uncaught exception to stderr; print would continue using stdout

**Comment by rwaldron** [comment]
@devsnek yep, that does work. I was overthinking it ;)
